"""Build the Extension application, guided installer, and portable ZIP."""
import json
import shutil
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
BUILD = HERE / "build"
RAW = HERE / "dist" / "_extension_raw"
RELEASE = HERE / "dist" / "Fxxk_Puzzle-extension"
INSTALLER = HERE / "installer"
NATIVE = INSTALLER
NATIVE_BUILD = NATIVE / "build"


def run(*args):
    subprocess.run([sys.executable, "-m", "PyInstaller", "--noconfirm", *args],
                   check=True, cwd=HERE)


def validate_positions(path: Path):
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise RuntimeError("缺少有效的 browser_positions.json，请先完成作者校准") from exc
    if value.get("schema") != 2 or value.get("window_mode") != "maximized":
        raise RuntimeError("定位参数不是最大化窗口 v2 格式，请重新校准 Chrome 和 Edge")
    for browser in ("chrome", "edge"):
        for action in ("developer_mode", "load_unpacked"):
            point = value.get(browser, {}).get(action)
            if (not isinstance(point, list) or len(point) != 2 or
                    not all(isinstance(item, (int, float)) and 0 <= item <= 1 for item in point)):
                raise RuntimeError(f"缺少有效定位参数：{browser}.{action}")
    return value


def write_native_positions(value):
    chrome = value["chrome"]
    edge = value["edge"]
    content = f'''#pragma once

// Generated by build.py from browser_positions.json.
struct BrowserPoints {{
    double developer_x;
    double developer_y;
    double load_x;
    double load_y;
}};

inline constexpr BrowserPoints kChromePoints{{{chrome["developer_mode"][0]:.6f}, {chrome["developer_mode"][1]:.6f}, {chrome["load_unpacked"][0]:.6f}, {chrome["load_unpacked"][1]:.6f}}};
inline constexpr BrowserPoints kEdgePoints{{{edge["developer_mode"][0]:.6f}, {edge["developer_mode"][1]:.6f}, {edge["load_unpacked"][0]:.6f}, {edge["load_unpacked"][1]:.6f}}};
'''
    (NATIVE / "generated_positions.hpp").write_text(content, encoding="utf-8")


def build_native_installers():
    subprocess.run(
        ["cmd.exe", "/d", "/c", str(NATIVE / "build_native.cmd")],
        check=True,
        cwd=NATIVE,
    )


def main():
    positions = INSTALLER / "browser_positions.json"
    position_values = validate_positions(positions)
    for path in (BUILD, RAW, RELEASE, NATIVE_BUILD):
        if path.exists():
            shutil.rmtree(path)
    RAW.mkdir(parents=True)
    write_native_positions(position_values)

    run("--clean", "--distpath", str(RAW), "--workpath", str(BUILD / "app"),
        str(HERE / "Fxxk_Puzzle.spec"))
    build_native_installers()

    RELEASE.mkdir(parents=True)
    shutil.copytree(RAW / "Fxxk_Puzzle", RELEASE / "app")
    shutil.copytree(HERE / "browser_extension", RELEASE / "extensions")
    shutil.copy2(NATIVE_BUILD / "Setup.exe", RELEASE / "Setup.exe")
    shutil.copy2(NATIVE_BUILD / "Uninstall.exe", RELEASE / "Uninstall.exe")
    shutil.copy2(HERE / "README.md", RELEASE / "README.md")
    shutil.make_archive(str(HERE / "dist" / "Fxxk_Puzzle-extension-portable"), "zip",
                        root_dir=RELEASE.parent, base_dir=RELEASE.name)
    shutil.rmtree(RAW)
    shutil.rmtree(BUILD)
    shutil.rmtree(NATIVE_BUILD)
    print(f"Built {RELEASE}")


if __name__ == "__main__":
    main()
