#pragma once

// Generated by build.py from browser_positions.json.
struct BrowserPoints {
    double developer_x;
    double developer_y;
    double load_x;
    double load_y;
};

inline constexpr BrowserPoints kChromePoints{0.979360, 0.140655, 0.062951, 0.209056};
inline constexpr BrowserPoints kEdgePoints{0.180083, 0.922929, 0.615067, 0.292871};
